<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu-admin</title>
</head>
<body>
<div class="all_header_menu">
    <div class="Logo">CATALOG</div>
    <div class="top_menu">
        <ul>
            <li id="id"><a href="/posts">
                    <div class="button_text">Выйти с панели администратора</div>
                </a></li>
        </ul>
    </div>
</div>

</body>
</html>